### ISSUE TITLE
Ability to allow same Flow emission

### ISSUE THREAD

**Issue by mochadwi** [pedroql/mvflow#30]
We're implementing our click events (e.g: `buttonA`), but unable to (re)click the `buttonA` unless we're resetting the events/click another events

The `buttonA` is just a simple showing bottom dialog, we're providing an ID to its intent then fetch API and display the data retrieved from server

Is it possible to allow same flow emission for particular/specific events? or should we implement reset state instead manually?

**Comment by pedroql** [comment]
It's hard to tell what problem you are facing. The library shouldn't restrict that so it's probably something else that causes the behaviour you see.

I can recommend checking the [sample app](https://github.com/pedroql/mvflow/tree/master/samples/android-app/src/main/kotlin/net/pedroloureiro/mvflow/samples/android/screens) that does that already and also reading this page of the docs: [Implementing your view actions flow](https://pedroql.github.io/mvflow/implementing-your-view-actions-flow/)

**Comment by mochadwi** [comment]
The reason our code unable to have same emissions due to the state is not changing when we clicks that `buttonA`. 

Is it possible to have same `data class State` value even though it's not changing?

> the reason we're manually resetting the state was to mutate the `data class State` so it's able to click again in `buttonA`

Will look for more samples on your code, I've found so far at the counter samples, the `data class State` is always has a new value.

**Comment by pedroql** [comment]
> Is it possible to have same data class State value even though it's not changing?

If I understand what you are saying correctly, this is breaking one of the core principles of MVI (not just of this library). If the state doesn't change, there is no reason to update the UI so we shouldn't emit a new state. The state needs to represent everything in the screen and there can be no difference in terms of UI if you render the same state (regardless of previous states, for example). 

If something in the UI needs to change, you need to make that part of the state; otherwise if you just want to make something like showing a Toast or launching another screen, you can use [effects](https://pedroql.github.io/mvflow/#special-effects). 

To be clear, your handler will still receive the actions (initially I understood that the handler wasn't receiving them). So then the handler can either emit a mutation that indeed changes the state from the previous value or it can emit an effect.

**Comment by mochadwi** [comment]
Ah, I see, so for our particular cases, the `effect` seems fit for multiple same event, e.g: showing a toast/dialog (user able to click it multiple times, even though there's no need to mutate a state) without the needs to reset our state manually or changing that particular state
